UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Controllers/AdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.Models.UnitOfWork;

namespace WebApp.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        private IUnitOfWork _unitOfWork;

        public AdminController()
        {
            _unitOfWork = new UnitOfWork();
        }
        public ActionResult Index()
        {
            ViewBag.Paths = GetUrlsForSliderImages();
            return View();
        }
        private string[] GetUrlsForSliderImages()
        {
            //string[] extensions = new[] { "jpeg", "jpg", "png", "bmp" };

            string[] paths = Directory.GetFileSystemEntries(HttpContext.Server.MapPath("/Content/Sources/img/slides"));
            for (int i = 0; i < paths.Length; i++)
            {
                int index = paths[i].LastIndexOf('\\');
                paths[i] = "/Content/Sources/img/slides" + paths[i].Substring(index, paths[i].Length - index);
            }
            return paths;
        }

        public void DeleteSlideImage(string ImageSRC)
        {
            FileInfo file = new FileInfo(HttpContext.Server.MapPath(ImageSRC));
            file.Delete();
        }

        [HttpPost]
        public ActionResult AddSlideImage(HttpPostedFileBase File)
        {
            File.SaveAs(HttpContext.Server.MapPath("/Content/Sources/img/slides")+ "/" + File.FileName);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Users()
        {
            var Users = new ApplicationDbContext().Users.ToList();
            var allRoles = new ApplicationDbContext().Roles.ToList();
            return View(Users);
        }

        public ActionResult DeleteUser(Guid UserId)
        {
            var user=_unitOfWork.Users.SingleOrDefault(u=>u.Id==UserId.ToString());
            _unitOfWork.Users.Remove(user);
            _unitOfWork.SaveChanges();
            return RedirectToAction("Users");
        }

        public void DeleteComment(Guid CommentId)
        {
            var comment = _unitOfWork.Comments.Get(CommentId);
            _unitOfWork.Comments.Remove(comment);
            _unitOfWork.SaveChanges();
        }     

    }
}

UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Controllers/PropertysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models.Entities;
using WebApp.Models.UnitOfWork;

namespace WebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class PropertysController : Controller
    {
        private IUnitOfWork _unitOfWork;

        public PropertysController()
        {
            _unitOfWork = new UnitOfWork();
        }

        public ActionResult Index()
        {
            return View(_unitOfWork.Properties.GetAll().OrderBy(property => property.Name));
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property property = _unitOfWork.Properties.Get(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        public ActionResult Create(Guid? TypeId)
        {
            ViewBag.TypeId = TypeId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Property property, Guid? TypeId)
        {
            if (_unitOfWork.Properties.Count(p => p.Name == property.Name) != 0)
                ModelState.AddModelError("", "Властивість з таким іменем вже існує");

            if (ModelState.IsValid)
            {
                property.Id = Guid.NewGuid();
                _unitOfWork.Properties.Add(property);
                if (TypeId != null)
                    _unitOfWork.Types.Get(TypeId).Properties.Add(property);
                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeId = TypeId;
            return View(property);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property property = _unitOfWork.Properties.Get(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Property property)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Properties.Update(property);
                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(property);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property property = _unitOfWork.Properties.Get(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Property property = _unitOfWork.Properties.Get(id);
            if (property.Types.Count != 0)
                ModelState.AddModelError("", "You cannot delete this property, because some type use it");
            if (property.Descriptions.Count != 0)
                ModelState.AddModelError("", "You cannot delete this property, because some product have description for this property");
            if (ModelState.IsValid)
            {
                _unitOfWork.Properties.Remove(property);
                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(property);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
<h2>Hello Admin!</h2>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Settings</h3>
    </div>
    <div class="panel-body">
        <div class="btn-toolbar">
            @Html.ActionLink("Users", "Users", "Admin", null, htmlAttributes: new { @class = "btn btn-dafault" })
            @Html.ActionLink("Types", "Index", "Types", null, htmlAttributes: new { @class = "btn btn-dafault" })
            @Html.ActionLink("Properties", "Index", "Propertys", null, htmlAttributes: new { @class = "btn btn-dafault" })
            @Html.ActionLink("Items", "Index", "Items", null, htmlAttributes: new { @class = "btn btn-dafault" })
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <div class="pull-left">
                <h3 >Images for slider</h3>
            </div>
            <div class="pull-right">
                <button id="fileupload" class="btn btn-primary">+</button>
            </div>
            <div style="clear:both;"></div>
        </div>

    </div>
    <div class="panel-body">
        <div class="btn-toolbar" id="imageList">
                @foreach (var path in ViewBag.Paths)
                {
                    <div class="img-thumbnail text-center imageBox">
                        <img src="@path" width="300" height="120" /><br />
                        <input type="button" class="imgDelete btn btn-default bottom" value="Delete" data-img="@path" />
                    </div>
                }
        </div>
    </div>
</div>

<div style="display:none;">
    @using (Html.BeginForm("AddSlideImage", "Admin", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data", @id = "temporaryForm" }))
    {
        <input type='file' id='file' name='File' accept='image/jpeg,image/gif,image/x-png' />
        <input type="submit" id="submitImageForm" />
    }
</div>

@Scripts.Render("~/bundles/bootbox")
<script src="~/Scripts/Admin/index.js"></script>
<link rel="stylesheet" href="~/Content/Admin/index.css" />

UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Views/Admin/Users.cshtml
@model IEnumerable<WebApp.Models.ApplicationUser>

@{
    ViewBag.Title = "Users";
}

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/datatable")
@Styles.Render("~/bundles/datatablecss")
@Scripts.Render("~/bundles/bootbox")
<script src="~/Scripts/Admin/Users.js"></script>
<h2>Users</h2>

<table class="table" id="UserDataTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccessFailedCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                Role
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccessFailedCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                @if (Roles.IsUserInRole(item.UserName, "admin"))
                {
                <td>
                     <label>Admin</label>
                </td>
                <td>
                </td>
                }
                else
                {
                    <td>
                        <label>User</label>
                    </td>
                    <td>
                        <button type="button" data-userid="@item.Id" class="btn btn-default deleteUser">Delete</button>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>