UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Controllers/TypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.Models.Entities;
using WebApp.Models.UnitOfWork;

namespace WebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class TypesController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public TypesController()
        {
            _unitOfWork = new UnitOfWork();
        }

        public ActionResult Index()
        {
            return View(_unitOfWork.Types.GetAll().Where(t=>t.Id!=Guid.Empty).ToList().OrderBy(type=>type.Name));
        }

        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Entities.Type type = _unitOfWork.Types.Get(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            ViewBag.IsParent = _unitOfWork.Types.IsThisTypeAsParent(id);
            return View(type);
        }

        public ActionResult Create()
        {
            ViewBag.Types = _unitOfWork.Types.GetAll().Where(type=>type.Items.Count()==0 && type.Id!=Guid.Empty);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ParentTypeId")] Models.Entities.Type type, HttpPostedFileBase File)
        {
            if(_unitOfWork.Types.Count(t=>t.Name==type.Name)!=0)
            {
                ModelState.AddModelError("", "Type with name '" + type.Name+ "' already exists!");
            }
            if (File != null)
            {
                Image Image = new Image()
                {
                    Id = Guid.NewGuid(),
                    ImageType = File.ContentType,
                    Name = File.FileName,
                    Data = new byte[File.ContentLength]
                };
                File.InputStream.Read(Image.Data, 0, File.ContentLength);
                type.Image = Image;
            }
            if (ModelState.IsValid)
            {
                type.Id = Guid.NewGuid();
                
                _unitOfWork.Types.Add(type);

                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Types = _unitOfWork.Types.GetAll().Where(t =>type.Items.Count() == 0 && type.Id!=Guid.Empty);
            return View(type);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Entities.Type type = _unitOfWork.Types.Get(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            var types = _unitOfWork.Types.Where(t => (t.Id != id) && (t.Items.Count()==0) && (t.ParentTypeId == null ? true : (t.ParentTypeId == id ? false : true)));
            List<SelectListItem> sListItems = new List<SelectListItem>();
            foreach(var Type in types)
            {
                sListItems.Add(new SelectListItem() { Value = Type.Id.ToString(), Text = Type.Name, Selected = (Type.Id == type.ParentTypeId) });
            }
            ViewBag.ParentTypeId = sListItems;
            return View(type);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ParentTypeId")] Models.Entities.Type type, Guid? OldImageId, HttpPostedFileBase File)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Types.Update(type);
                _unitOfWork.SaveChanges();
                if (File != null)
                {
                    var t = _unitOfWork.Types.Get(type.Id);
                    if (OldImageId == null)
                    {
                        Image Image = new Image()
                        {
                            Id = Guid.NewGuid(),
                            ImageType = File.ContentType,
                            Name = File.FileName,
                            Data = new byte[File.ContentLength]
                        };
                        File.InputStream.Read(Image.Data, 0, File.ContentLength);
                        _unitOfWork.Images.Add(Image);
                        _unitOfWork.SaveChanges();
                        type.Image = Image;
                        _unitOfWork.Types.Update(type);
                        _unitOfWork.SaveChanges();
                    }
                    else
                    {
                        var oldImage = _unitOfWork.Images.Get(OldImageId);
                        oldImage.ImageType = File.ContentType;
                        oldImage.Name = File.FileName;
                        oldImage.Data = new byte[File.ContentLength];
                        File.InputStream.Read(oldImage.Data, 0, File.ContentLength);
                        _unitOfWork.Images.Update(oldImage);
                        _unitOfWork.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }
            return View(type);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Entities.Type type = _unitOfWork.Types.Get(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Models.Entities.Type type = _unitOfWork.Types.Get(id);
            if (_unitOfWork.Types.IsThisTypeAsParent(id))
            {
                ModelState.AddModelError("", "You can not remove this type because he has descendant types");
            }
            if(type.Items.Count!=0)
            {
                ModelState.AddModelError("", "You can not remove this type. Exist products of this type");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Types.Remove(type);
                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(type);
        }

        [HttpGet]
        public ActionResult RemoveProperty(Guid TypeId, Guid PropertyId)
        {
            _unitOfWork.Types.Get(TypeId).Properties.Remove(_unitOfWork.Properties.Get(PropertyId));
            _unitOfWork.SaveChanges();
            return RedirectToAction("Details", new { Id = TypeId });
        }

        public JsonResult AddProperty(Guid TypeId, string PropertyName)
        {
            bool Error = false;
            string id = "";
            if(_unitOfWork.Properties.Count(property=>property.Name==PropertyName)!=0)
            {
                Error = true;
            }
            if(!Error)
            {
                Property Property = new Property()
                {
                    Id = Guid.NewGuid(),
                    Name = PropertyName
                };
                _unitOfWork.Types.Get(TypeId).Properties.Add(Property);
                _unitOfWork.SaveChanges();
                id = Property.Id.ToString();
            }
            return Json(new { Error = Error, Id = id}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ChangeConnectionBetweenTypeAndProperties(Guid TypeId)
        {
            ViewBag.TypeId = TypeId;
            var type = _unitOfWork.Types.Get(TypeId);
            ViewBag.TypeName = type.Name;
            var properties = _unitOfWork.Properties.GetAll().Select(p => new { Property = p, IsChecked = type.Properties.Any(pr => pr.Id == p.Id) }).ToDictionary(x => x.Property, x => x.IsChecked);
            return View(properties);
        }

        [HttpPost]
        public void ChangeConnectionBetweenTypeAndProperties(Guid TypeId, Guid PropertyId, bool Checked)
        {
            if (Checked)
                _unitOfWork.Types.Get(TypeId).Properties.Add(_unitOfWork.Properties.Get(PropertyId));
            else
                _unitOfWork.Types.Get(TypeId).Properties.Remove(_unitOfWork.Properties.Get(PropertyId));
            _unitOfWork.SaveChanges();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Views/Types/ChangeConnectionBetweenTypeAndProperties.cshtml
@model Dictionary<WebApp.Models.Entities.Property, bool>
@{
    ViewBag.Title = "ChangeConnectionBetweenTypeAndProperties";
}

<h2>Change connection between the type and properties</h2>

<input type="hidden" value="@ViewBag.TypeId" name="TypeId" id="TypeId" />
<h2>@ViewBag.TypeName</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Checked
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var property in Model)
        {
            <tr>
                <td>
                    @property.Key.Name
                </td>
                <td>
                    @Html.CheckBox("checkBox", property.Value, new { @data_propid = property.Key.Id, @class = "checkForProperty" })
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.ActionLink("Details", "Details", new { id = ViewBag.TypeId })

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).on('change', ".checkForProperty", function () {
        var checked = false;
        var TypeId = $("#TypeId").val();
        var PropertyId = $(this).data("propid");
        if ($(this).is(":checked")) {
            checked = true;
        }
        $.post("/types/ChangeConnectionBetweenTypeAndProperties", {TypeId: TypeId, PropertyId: PropertyId, Checked: checked});
    });
</script>

UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Views/Types/Create.cshtml
@model WebApp.Models.Entities.Type

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Types", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Type</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
                
        <div class="form-group">
            @Html.LabelFor(model => model.ParentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="ParentTypeId" name="ParentTypeId" class = "form-control">
                    @foreach(var type in ViewBag.Types)
                    {
                        <option value="@type.Id">
                            @type.Name
                        </option>
                    }
                    <option value="@Guid.Empty" selected="selected">
                        None
                    </option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Type image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="File" />   
            </div>
        </div>        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Views/Types/Delete.cshtml
@model WebApp.Models.Entities.Type

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Type</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> <br />
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Views/Types/Details.cshtml
@model WebApp.Models.Entities.Type

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Type</h4>
    <input type="hidden" value="@Model.Id" name="TypeId" id="TypeId" />
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        @if (Model.ParentType != null)
        {
        <dt>
            @Html.DisplayNameFor(model => model.ParentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentType.Name)
        </dd>
        }
        @if (Model.Image != null)
        { 
        <dt>
            Image
        </dt>

        <dd>
            <img src="@Url.Action("GetImage", "Home", new { ImageId = Model.Image.Id })" alt="@Model.Image.Name" height="150" />
        </dd>
        }
    </dl>
    <H2>Властивості</H2>
    @if (ViewBag.IsParent == false)
    {
        <p>
            <button type="button" class="btn btn-primary" id="newProperty">Add new property</button>
            @Html.ActionLink("Add/Remove properties", "ChangeConnectionBetweenTypeAndProperties", new { TypeId = Model.Id }, htmlAttributes: new { @class="btn btn-primary", @data_toggle = "tooltip", @title = "Change connection between Type and Properties" })
        
        </p>
    }
    <table class="table">
        <thead>
            <tr>
                <th>
                    Назва
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var property in Model.Properties)
            {
                <tr>
                    <td>
                        @property.Name
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary deleteProperty pull-right" data-propertyid="@property.Id">x</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@Scripts.Render("~/bundles/bootbox")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/toastr")
@Styles.Render("~/bundles/toastrcss")
<script src="~/Scripts/Types/Details.js"></script>

UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Views/Types/Edit.cshtml
@model WebApp.Models.Entities.Type

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Types", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Type</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentTypeId", ViewBag.ParentTypeId as SelectList, @*Model.ParentType.Name ?? "None",*@ new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Type image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model.Image != null)
                {
                    <input type="hidden" name="OldImageId" value="@Model.Image.Id" />
                    <img src="@Url.Action("GetImage", "Home", new { ImageId = Model.Image.Id })" alt="@Model.Image.Name" height="150" id="Image" />
                    <input type="file" name="File" placeholder="click to change image" id="file" />
                }
                else
                {
                    <input type="file" name="File" />
                }
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
}
@Scripts.Render("~/bundles/jquery")
<script>
    $(document).ready(function () {
        $(document).on('change', "#file", function () {
            $('#Image').hide();
        });
    
    });
    
</script>

UniversalCatalog/UniversalCatalog/UniversalCatalog/WebApp/Views/Types/Index.cshtml
@model IEnumerable<WebApp.Models.Entities.Type>

@{
    ViewBag.Title = "Types";
}



@Scripts.Render("~/bundles/datatable")
@Styles.Render("~/bundles/datatablecss")
<h2>Types</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="datatable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ParentType)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Name, "Details", new { id = item.Id })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ParentType.Name)
                </td>
                <td>
                    <div class="btn-group">
                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Edit", "Edit", new { id = item.Id })</li>
                            <li>@Html.ActionLink("Delete", "Delete", new { id = item.Id })</li>
                        </ul>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#datatable').DataTable();
    });
</script>